# This is a basic workflow to help you get started with Actions

name: EMS test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
          fetch-depth: 0 # 0 indicates all history
      - run: git fetch --all || echo "==> Accept any result"
#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
          
          
          
#       - name: upload to s3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks
#         env:
#           AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_SECRET}}
#           AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
#           SOURCE_DIR: 'dir'      # optional: defaults to entire repository
                 
      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: dir/test-json.json
          S3_ENDPOINT: 'eu-west-1'
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_SECRET }}
